name: Deploy to Linode

on:
  push:
    branches:
      - master

env:
  LINODE_SSH_KEY: ${{ secrets.LINODE_SSH_KEY }}
  LINODE_USER: ${{ secrets.LINODE_USER }}
  LINODE_IP: ${{ vars.LINODE_IP }}
  PROJECT_PATH: ${{ secrets.PROJECT_PATH }}
      
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: SSH setup
        run: |
          mkdir -p ~/.ssh/
          echo "$LINODE_SSH_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          echo $LINODE_IP
          ssh-keyscan -H $LINODE_IP >> ~/.ssh/known_hosts

      - name: Git Pull and Restart PM2
        run: |
          ssh $LINODE_USER@$LINODE_IP "cd $PROJECT_PATH && git pull && pm2 restart all"

        
